CREATE DATABASE IF NOT EXISTS rosdb DEFAULT CHARACTER SET utf8mb4;
USE rosdb;

CREATE TABLE IF NOT EXISTS turtlepos (
    id    INT AUTO_INCREMENT PRIMARY KEY,
    x     DOUBLE   NOT NULL,
    y     DOUBLE   NOT NULL,
    theta DOUBLE   NOT NULL,
    `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
